### ISSUE TITLE
typescript definitions

### ISSUE THREAD

**Issue by download13** [benji6/cycle-audio-graph#3]
Would it be possible to [add some typescript definitions](https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html) to this repository?

**Comment by benji6** [comment]
yep, this should be possible, let me take a look

**Comment by benji6** [comment]
I've just published cycle-audio-graph v1.1.0 which should include the newly added type declaration file https://github.com/benji6/cycle-audio-graph/commit/fb6905d0d047902590f065c65b69d2c1b7b4f1dd (first release in a couple years! 😬 )

The type declarations are a bit lazy - as you can see I've used `any`. I'm wondering how important it is for you to have really accurate types? That would probably end up being a bit more work and taking some time

**Comment by benji6** [comment]
Haven't heard back on this issue so will close for now, feel free to reopen if needed
